language: node_js

os:
  - linux
  - windows

node_js:
  - "8"
  - "10"
  - "12"
  - "14"

jobs:
  include:
    # test coverage run
    - os: linux
      node_js: "14"
      script: npm run test-with-coverage
      after_success: ./node_modules/.bin/codecov

script:
- npm test
